server:
  port: 3306

spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/sec
    username: root
    password: admin
  flyway:
    url: jdbc:mysql://localhost:3306/sec
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    cloud:                                  #//# AWS S3 configuration
      aws:
        credentials:
          aws_access_key_id: your-access-key
          aws_secret_access_key: your-secret-key
        region: us-west-2
        endpoint: https://s3.us-west-2.amazonaws.com

jwt:
  password:
    encoder:
      secret: FZK2DZ82odqS13e8aENggaMbb_fAkl-nJL4AEVBX43g
      iteration: 64
      keylength: 256
  secret: b5f59337a612a2a7dc07328f3e7d1a04722967c7f06df20a499a7d3f91ff2a7e
  expiration: 3600
  issuer: example


# Security public routes
security:
  publicRoutes:
    - "/login"
    - "/register"
    - "/public/**"